### PR TITLE
Fix vendor interop tests.

### PR DESCRIPTION
**Pull request by OR13**

### CODE REVIEW

**Comment by OR13** [comment]
@msporny @troyronda  it would be awesome to have another vendor to test against.

**Comment by msporny** [comment]
> @msporny @troyronda it would be awesome to have another vendor to test against, especially given #99 ... we would like to maintain compatibility, and it looks like a server side interface was just broken.

What do you need for that to happen? Us to put up one of our EDV servers at a public endpoint?

**Comment by OR13** [comment]
@msporny yep, pretty much just need an opaque version of your edv software running on a public endpoint... it can be regularly reset... similar to how we tested the vc http apis...

**Comment by msporny** [comment]
> @msporny yep, pretty much just need an opaque version of your edv software running on a public endpoint... it can be regularly reset... similar to how we tested the vc http apis...

Ok, thanks for the solid ask... I'll bring this up during one of our standups.

What we'd like to see, and I expect you agree, is a CI-CD process that tests the latest implementations against a test suite on a nightly basis so we can all know how we're doing from an interop perspective. We didn't do this in the VC WG and DID WG... and it became a problem. Perhaps we can get it right this time around.

**Comment by OR13** [comment]
@msporny yes, you would have seen breaking changes when you published 5.0 if you had CI pipeline that was running your client against our (and others) servers... thats what these tests are doing :)

IMO thats ok as long as we agreed to it, and at least 1 vendor is proved to be passing 5.0 ...

Currently we are just crossing our fingers and hoping you guys are :)

**Comment by msporny** [comment]
> Currently we are just crossing our fingers and hoping you guys are :)

Don't worry, we're crossing our fingers two. So, we've got at least two implementers crossing our fingers, that counts for something, right? :P

**Pull request merged**
