### PR TITLE
Add example data vault client

### PR DESCRIPTION
**Pull request by OR13**
Add code and fixtures for vault config

### CODE REVIEW

**Review by msporny — APPROVED** [review]
+1 to an example data vault client.

-1 to mixing specs + code in same repo, but I'm not going to stand in the way of code being written and committed.

**Comment by OR13** [comment]
> +1 to an example data vault client.
> 
> -1 to mixing specs + code in same repo, but I'm not going to stand in the way of code being written and committed.

The problem is that test fixtures are actually what enable interoperability, and generating them from code and checking them into source is the least amount of work for the most confidence that they have not changed.

My plan with this code is to generate the test fixtures that the spec will normatively reference... not to write another data vault client.... although a significant amount of code duplication will be required to achieve spanning test vectors.

**Comment by msporny** [comment]
> The problem is that test fixtures are actually what enable interoperability, and generating them from code and checking them into source is the least amount of work for the most confidence that they have not changed.

I'm almost blindly trusting you on this assertion. I'm not entirely sure what you mean by "test fixtures" -- there is a testing pattern that you use that I haven't had the time to wrap my head around. It sounds truthy, but is different from other test harnesses I've seen for W3C specs. I'm willing to go along with this because you're doing the work and we shouldn't get in the way of people doing the work. Is there some sort of write up wrt. "test fixtures" philosophy that you can point to that would be a good introduction?

If by "test fixtures" you mean -- "things that, when your program does its operations, should result in the test fixtures", then I know exactly what you mean and those are typically called "test vectors" or "test cases". If you mean something else, then this is probably some new fangled approach to testing that I'm unaware of... :)

**Comment by OR13** [comment]
@msporny this RFC is what I am talking about: https://tools.ietf.org/html/rfc7520

Its really hard to know if your software "implements a standard" if you can't all check inputs and outputs, and make sure they are the same.

Imagine reading a spec, and then trying to write 5 different implementations of the spec, that all need to match up without having some data that they were all supposed to be capable of handling / producing... 

Then imagine someone keeps changing that data, because it's not version controlled next to the spec.

Thats what I want to avoid.

**Comment by msporny** [comment]
> @msporny this RFC is what I am talking about: https://tools.ietf.org/html/rfc7520

Ah, yes... I call those "test vectors"... :)

> yes, `test-fixtures/ test-vectors / test-cases`... they need to be committed to source :)

+1

> its nice to automatically generate them from software, so they are easy to update all at once, and so you know at least 1 piece of software can produce them.

+1

> Its really hard to know if your software "implements a standard" if you can't all check inputs and outputs, and make sure they are the same.

+1, and I argue should be the purpose of test suites at W3C. There is an argument that a test suite should "test the specification"... but I think we should go further and test implementations, not the spec. I believe we're testing implementations w/ the SDS WG work, which is a great expectation to set from the beginning.

> Imagine reading a spec, and then trying to write 5 different implementations of the spec, that all need to match up without having some data that they were all supposed to be capable of handling / producing...

Yep, nightmare that we want to avoid.

> Then imagine someone keeps changing that data, because it's not version controlled next to the spec.

Agree, not easy for people to understand whether or not they're conformant.

> Thats what I want to avoid.

+1 -- now I think I understand what you mean by "test fixtures" and I'll just replace that word in my brain with "test vectors" when you say it. :)

**Comment by OR13** [comment]
> +1 -- now I think I understand what you mean by "test fixtures" and I'll just replace that word in my brain with "test vectors" when you say it. :)

haha yep... naming matters... for me a fixture becomes a test vector when it gets knighted by being laid out in an RFC / published spec... until then, its just a lowly squire fixture.... and subject to change as the spec / implementations and tests change.... which hopefully ends at some point :)

**Pull request merged**
